### ISSUE TITLE
Frecuencias de Di-tri nucleotidos

### ISSUE THREAD

**Issue by lbernaz** [mathiashole/identifyMuFa#2]
Hacer las frecuencias dinucleotidos y trinucleotidos, sumando el complementario reverso, y hacer PCA y T-SNE, solo con las dgf1 de los distintos genomas, y con cada genoma pintando las DGF1 en el cada grafico para cada genoma
@mathiashole

**Comment by mathiashole** [comment]
Hecho @lbernaz
